#მომხმარებელს შემოატანინეთ ორი რიცხვი გააკეთეთ მათზე მათემატიკური ოპერაციები  ("+, -, *, /, %, <, >, <=, >=, ==, !=. **)
num1 = int(input('Enter Any Number: '))
num2 = int(input('Enter Any Number: '))
print(num1 + num2 )
print(num2 - num1 )
print(num1 * num2 )
print(num2 / num2 )
print(num1 % num2 )
print(num2 > num1 )
print(num1 < num2 )
print(num2 <= num2 )
print(num1 >= num2 )
print(num2 == num1 )
print(num1 != num2 )
print(num2 ** num2 )